In [10]:
import numpy as np
import math
from cmath import sqrt

In [11]:
x=np.array([5,20,25,70,115,145,185,200,206,220,290])

#how last value affect the calculation
xf=np.array([60,110,140,150,210,0])

D=np.array([10,10,5,15,12,0])
np.shape(x)
np.shape(xf)
np.shape(D)
pi = math.pi
print(pi)

3.141592653589793


In [12]:
v1f1 = np.arctan((x[0]-xf[0])/D[0])/pi
v2f1 = np.arctan((x[1]-xf[0])/D[0])/pi
v3f1 = np.arctan((x[2]-xf[0])/D[0])/pi
v4f1 = np.arctan((x[3]-xf[0])/D[0])/pi
v5f1 = np.arctan((x[4]-xf[0])/D[0])/pi
v6f1 = np.arctan((x[5]-xf[0])/D[0])/pi
v7f1 = np.arctan((x[6]-xf[0])/D[0])/pi
v8f1 = np.arctan((x[7]-xf[0])/D[0])/pi
v9f1 = np.arctan((x[8]-xf[0])/D[0])/pi
v10f1 = np.arctan((x[9]-xf[0])/D[0])/pi
v11f1 = np.arctan((x[10]-xf[0])/D[0])/pi

print(v1f1)
print(v11f1)

-0.44275085295129984
0.4861691504333381


In [13]:
v1f2 = np.arctan((x[0]-xf[1])/D[1])/pi
v2f2 = np.arctan((x[1]-xf[1])/D[1])/pi
v3f2 = np.arctan((x[2]-xf[1])/D[1])/pi
v4f2 = np.arctan((x[3]-xf[1])/D[1])/pi
v5f2 = np.arctan((x[4]-xf[1])/D[1])/pi
v6f2 = np.arctan((x[5]-xf[1])/D[1])/pi
v7f2 = np.arctan((x[6]-xf[1])/D[1])/pi
v8f2 = np.arctan((x[7]-xf[1])/D[1])/pi
v9f2 = np.arctan((x[8]-xf[1])/D[1])/pi
v10f2 = np.arctan((x[9]-xf[1])/D[1])/pi
v11f2 = np.arctan((x[10]-xf[1])/D[1])/pi

print(v1f2)
print(v11f2)

-0.4697759331610805
0.48233427711186533


In [14]:
v1f3 = np.arctan((x[0]-xf[2])/D[2])/pi
v2f3 = np.arctan((x[1]-xf[2])/D[2])/pi
v3f3 = np.arctan((x[2]-xf[2])/D[2])/pi
v4f3 = np.arctan((x[3]-xf[2])/D[2])/pi
v5f3 = np.arctan((x[4]-xf[2])/D[2])/pi
v6f3 = np.arctan((x[5]-xf[2])/D[2])/pi
v7f3 = np.arctan((x[6]-xf[2])/D[2])/pi
v8f3 = np.arctan((x[7]-xf[2])/D[2])/pi
v9f3 = np.arctan((x[8]-xf[2])/D[2])/pi
v10f3 = np.arctan((x[9]-xf[2])/D[2])/pi
v11f3 = np.arctan((x[10]-xf[2])/D[2])/pi

print(v1f3)
print(v11f3)

-0.48821613112965856
0.48939359759446455


In [15]:
v1f4 = np.arctan((x[0]-xf[3])/D[3])/pi
v2f4 = np.arctan((x[1]-xf[3])/D[3])/pi
v3f4 = np.arctan((x[2]-xf[3])/D[3])/pi
v4f4 = np.arctan((x[3]-xf[3])/D[3])/pi
v5f4 = np.arctan((x[4]-xf[3])/D[3])/pi
v6f4 = np.arctan((x[5]-xf[3])/D[3])/pi
v7f4 = np.arctan((x[6]-xf[3])/D[3])/pi
v8f4 = np.arctan((x[7]-xf[3])/D[3])/pi
v9f4 = np.arctan((x[8]-xf[3])/D[3])/pi
v10f4 = np.arctan((x[9]-xf[3])/D[3])/pi
v11f4 = np.arctan((x[10]-xf[3])/D[3])/pi
print(v1f4)
print(v11f4)

-0.4671881049234972
0.4660249801873033


In [16]:
v1f5 = np.arctan((x[0]-xf[4])/D[4])/pi
v2f5 = np.arctan((x[1]-xf[4])/D[4])/pi
v3f5 = np.arctan((x[2]-xf[4])/D[4])/pi
v4f5 = np.arctan((x[3]-xf[4])/D[4])/pi
v5f5 = np.arctan((x[4]-xf[4])/D[4])/pi
v6f5 = np.arctan((x[5]-xf[4])/D[4])/pi
v7f5 = np.arctan((x[6]-xf[4])/D[4])/pi
v8f5 = np.arctan((x[7]-xf[4])/D[4])/pi
v9f5 = np.arctan((x[8]-xf[4])/D[4])/pi
v10f5 = np.arctan((x[9]-xf[4])/D[4])/pi
v11f5 = np.arctan((x[10]-xf[4])/D[4])/pi
print(v1f5)
print(v11f5)

-0.4813884644583251
0.4526068577225104


In [17]:
G=np.matrix([[v1f1, v1f2, v1f3, v1f4, v1f5],
             [v2f1, v2f2, v2f3, v2f4, v2f5],
             [v3f1, v3f2, v3f3, v3f4, v3f5],
             [v4f1, v4f2, v4f3, v4f4, v4f5],
             [v5f1, v5f2, v5f3, v5f4, v5f5],
             [v6f1, v6f2, v6f3, v6f4, v6f5],
             [v7f1, v7f2, v7f3, v7f4, v7f5],
             [v8f1, v8f2, v8f3, v8f4, v8f5],
             [v9f1, v9f2, v9f3, v9f4, v9f5],
             [v10f1, v10f2, v10f3, v10f4, v10f5],
             [v11f1, v11f2, v11f3, v11f4, v11f5]])

np.shape(G)

(11, 5)

In [19]:
dim=np.matrix([-27,-27,-27,-20,-8,5,12,12,12,17,17])

In [30]:
t = dim.T*G
print(np.shape(t))
dT=dim.T
t

(1, 5)


matrix([[61.81722746, 79.92691791, 87.19673966, 78.4978935 , 53.10538803]])

In [31]:
print(type(G))
print(np.shape(G))
len(G)

<class 'numpy.matrix'>
(11, 5)


11

In [32]:
u,s,vh = np.linalg.svd(G.T, full_matrices=True)
len(s)
s

array([2.78562392, 1.40396765, 0.62286822, 0.30871162, 0.18113364])

In [33]:
sm = np.matrix([[s[0],0,0,0,0],
                [0,s[1],0,0,0],
                [0,0,s[2],0,0],
                [0,0,0,s[3],0],
                [0,0,0,0,s[4]]])
np.shape(sm)  

(5, 5)

In [34]:
sm
p=4
print(sm[0:p, 0:p])
sp=(sm[0:p, 0:p])

[[2.78562392 0.         0.         0.        ]
 [0.         1.40396765 0.         0.        ]
 [0.         0.         0.62286822 0.        ]
 [0.         0.         0.         0.30871162]]


In [35]:
print(np.shape(u))
print(np.shape(sm))
print(np.shape(vh))
#print(u,sm,vh)

(5, 5)
(5, 5)
(11, 11)


In [36]:
up=np.transpose(u[:,0:p])
sp=np.linalg.inv(sm[0:p,0:p])
vp=np.transpose(vh[0:p,:])

In [37]:
up
print(np.shape(up))
sp
print(np.shape(sp))
vp
print(np.shape(vp))

(4, 5)
(4, 4)
(11, 4)


In [38]:
Gg = vp*sp*up
np.shape(Gg)

(11, 5)

In [40]:
m=Gg*t.T

In [41]:
print(m.T)
print(dim)

[[-23.85084421 -23.6496789  -23.56340444 -20.86053089  -7.67370854
    4.3488754    9.66240333  12.18760681  14.20099787  19.60509833
   23.76194865]]
[-27 -27 -27 -20  -8   5  12  12  12  17  17]
