In [3]:
import numpy as np

In [4]:
A = np.matrix('1 2; -3 4')
B = np.matrix('-2 0; 1 0')
C = np.matrix('3 -2')
D = np.matrix('1; 4')
E = np.matrix('0 0; 3 4')

In [5]:
A + B

matrix([[-1,  2],
        [-2,  4]])

In [6]:
4*(A-B)

matrix([[ 12,   8],
        [-16,  16]])

In [7]:
(2+3)*A

matrix([[  5,  10],
        [-15,  20]])

In [8]:
C*D

matrix([[-5]])

In [9]:
A*D

matrix([[ 9],
        [13]])

In [10]:
D*A

ValueError: shapes (2,1) and (2,2) not aligned: 1 (dim 1) != 2 (dim 0)

In [11]:
np.transpose(D)*A

matrix([[-11,  18]])

In [12]:
np.transpose(np.transpose(D)*A)

matrix([[-11],
        [ 18]])

In [13]:
np.transpose(A)*A

matrix([[ 10, -10],
        [-10,  20]])

In [14]:
np.trace(A)

5

In [15]:
B*E

matrix([[0, 0],
        [0, 0]])

In [16]:
A*(B*D)

matrix([[ 0],
        [10]])

In [17]:
(A*B)*D

matrix([[ 0],
        [10]])

In [18]:
np.linalg.inv(A)

matrix([[ 0.4, -0.2],
        [ 0.3,  0.1]])

In [19]:
A*np.linalg.inv(A)

matrix([[1.00000000e+00, 2.77555756e-17],
        [0.00000000e+00, 1.00000000e+00]])

In [23]:
d1=np.linalg.norm(A-B, ord=1)
d1

7.0

In [24]:
d2=np.linalg.norm(A-B)
d2

6.708203932499369

In [26]:
r = np.corrcoef(A,B)[0,1]
r

1.0